[tool.poetry]
name = "helm-chart-kata"
version = "0.1.0"
description = ""
authors = ["Louis Sanna"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.2"
uvicorn = "^0.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
